### ISSUE TITLE
프로젝트 세부 설계

### ISSUE THREAD

**Issue by wnsxor1993** [PJJ-corp/Geulmoi#2]
- [x] Feature 설계
- [x] Core 설계
- [x] Shared 설계
- [ ] 머지 후, 디펜던시 적용

**Comment by junu0516** [comment]
@wnsxor1993 @Jeeehee 
Shared에는 Feature, Core 이외의 공통 로직이 기능단위로 나뉘어야 할 것 같은데..
실제로 기능개발에 들어가기 전에 어떤 종류 혹은 이름의 모듈이 넣을 지가 불분명합니다.

우선 예상해보는 바로는
    
1. 모든 계층에서 독립적으로 사용하기 위한 객체를 관리하는 DIContainer
2. MVVM 구조를 위한 ViewModel, View 등의 인터페이스
3. 기타 Util성 코드들
    
이렇게 3가지 정도를 예상해볼 수 있는데 3번은 실제로 기능개발 들어가면서 구현해야 할 것 같고,
1,2는 Feature, Core 구조가 어느정도 확실해지면 바로 정의해볼 수 있을 것 같습니다.

**Comment by wnsxor1993** [comment]
@junu0516 @Jeeehee 
각각 태스크 완료됐는지 확인하고 마무리되었으면 해당 이슈 닫으면 될 것 같습니당
